### ISSUE TITLE
Simplified Integration Does Not Work: Error 2207

### ISSUE THREAD

**Issue by soh2131** [xsolla/payments-unity-sdk#5]
Steps to Reproduce:
1. Download the SDK v1.0.0.0 released on Jul 7
2. Open Simplified Integration Scene in Unity
3. Hit Play and it works for default setting with default project ID set to 68789 and sandbox enabled.
4. Setup Account and project on Xsolla website, set integration mode to simplified integration with only Virtual Items enabled and 1 test item created.
5. Go back to Unity Xsolla setting and change project ID to the project ID we just created on the website.
6. Hit play and try purchase.
7. Showing Error 2207: Invalid User ID

**Comment by d-sidorenko** [comment]
Hi! 

Sorry for the late reply. 

This error could occur for Simplified Integration if catalogs in Xsolla Publisher Account and game client/demo are different. For this type of integration you should manually create an in-game catalog, since client is supposed to work without server side. You can see docs for it here: https://developers.xsolla.com/sdk/game-engines/unity/#unity_sdk_simplified_integration_set_up_items_list

Also, if you want a solution with catalog based only on Xsolla's side you can try Xsolla Store SDK: https://assetstore.unity.com/packages/tools/integration/xsolla-store-sdk-145141

Thanks for your question!
